### PR TITLE
remove rocm source files when not building for rocm

### LINKED ISSUE #2297: [Windows][build]two Build failure on Windows on latest main branch
hi,  team,
     when i try to build the torchao with the latest code, it will meet below two failures,
1.
 _× python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      W0603 21:46:20.257000 15024 site-packages\torch\distributed\elastic\multiprocessing\redirects.py:29] NOTE: Redirects are currently not supported in Windows or MacOs.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 35, in <module>
        File "C:\work\ao\setup.py", line 571, in <module>
          long_description=open("README.md").read(),
        File "C:\ProgramData\miniforge3\envs\torchao_2025.1\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 10945: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed_

i have triaged the issue, and found that it is the https://github.com/pytorch/ao/commit/adc78b72cf6f8b1bb47b21d8fa525048e24f3497 which introduced this regression, and the root cause is there is a ⚠️ in the Readme.MD and windows can not decode this. the solution is either remove this ⚠️ or modify the setup.py with long_description=open("README.md").read() to long_description=open("README.md", encoding='utf-8').read(). 

2. after i fix the above failure with remove the ⚠️ in Readme.MD, i meet another failure like below,
_LINK : error LNK2001: unresolved external symbol PyInit__C
        C:\work\ao\build\temp.win-amd64-cpython-310\Release\torchao\csrc\rocm\swizzle\_C.lib : fatal error LNK1120: 1 unresolved externals
        error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.43.34808\\bin\\HostX64\\x64\\link.exe' failed with exit code 1120_
i also triage this regression, and found it is introduced by https://github.com/pytorch/ao/commit/63f2e51bf034786a84259fe39e2e743285f51dda

could you please help to fix them?

### PR DESCRIPTION
**Pull request by jeffdaily**
fixes #2297

### CODE REVIEW

**Comment by msaroufim** [comment]
This worked for me locally on Windows

```
    Found existing installation: torchao 0.12.0+gitc6e920b1
    Uninstalling torchao-0.12.0+gitc6e920b1:
      Successfully uninstalled torchao-0.12.0+gitc6e920b1
Successfully installed torchao-0.12.0+gitc6e920b1
(ao) PS C:\Users\Mark\Dev\ao> 
```

Granted the source inclusion/exclusion logic is kinda confusing to me now and this whole file is probably due for a refactor
