### ISSUE TITLE
Creation of MXFP8 Tensor fails with AttributeError: module 'torch' has no attribute 'float8_e8m0fnu'

### ISSUE THREAD

**Issue by avizon-aws** [pytorch/ao#2783]
I tried to reproduce the code snippet from the tutorial: https://github.com/pytorch/ao/tree/main/torchao/prototype/mx_formats#mxtensor:~:text=Coming%20soon!-,MXTensor,-This%20is%20casts

And I see the error: 
AttributeError: module 'torch' has no attribute 'float8_e8m0fnu'.

Is this expected? because the PR for supporting E8M0 was merged: https://github.com/pytorch/pytorch/pull/147466 long back.

**Comment by avizon-aws** [comment]
Never mind, it works with torch 2.7
