### ISSUE TITLE
`AttributeError: module 'torch._inductor' has no attribute 'config'` after upgrading to 0.8

### ISSUE THREAD

**Issue by vgoklani** [pytorch/ao#1613]
I just upgraded to torchao 0.8 from 0.7

```bash
pip install -U torchao
```

and i see this after importing:

```python
In [1]: import torchao
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 1
----> 1 import torchao

File /usr/local/lib/python3.12/dist-packages/torchao/__init__.py:50
     47     except:
     48         logging.debug("Skipping import of cpp extensions")
---> 50 from torchao.quantization import (
     51     autoquant,
     52     quantize_,
     53 )
     55 from . import dtypes, testing
     57 __all__ = [
     58     "dtypes",
     59     "autoquant",
   (...)
     62     "ops",
     63 ]

File /usr/local/lib/python3.12/dist-packages/torchao/quantization/__init__.py:7
      1 # Copyright (c) Meta Platforms, Inc. and affiliates.
      2 # All rights reserved.
      3
      4 # This source code is licensed under the license found in the
      5 # LICENSE file in the root directory of this source tree.
----> 7 from torchao.kernel import (
      8     int_scaled_matmul,
      9     safe_int_mm,
     10 )
     12 from .autoquant import (
     13     ALL_AUTOQUANT_CLASS_LIST,
     14     DEFAULT_AUTOQUANT_CLASS_LIST,
   (...)
     20     autoquant,
     21 )
     22 from .GPTQ import (
     23     Int4WeightOnlyGPTQQuantizer,
     24     Int4WeightOnlyQuantizer,
   (...)
     27     Int8DynActInt4WeightQuantizer,
     28 )

File /usr/local/lib/python3.12/dist-packages/torchao/kernel/__init__.py:1
----> 1 from torchao.kernel.intmm import int_scaled_matmul, safe_int_mm
      3 __all__ = [
      4     "safe_int_mm",
      5     "int_scaled_matmul",
      6 ]

File /usr/local/lib/python3.12/dist-packages/torchao/kernel/intmm.py:10
      7 try:
      8     # Only works for torch2.2 or newer.
      9     if TORCH_VERSION_AT_LEAST_2_2:
---> 10         from torchao.kernel import intmm_triton
     11     else:
     12         intmm_triton = None

File /usr/local/lib/python3.12/dist-packages/torchao/kernel/intmm_triton.py:37
     11 int8_mm_kernel_configs = sum(
     12     [
     13         # "BLOCK_M", "BLOCK_N", "BLOCK_K", "num_stages", "num_warps"
   (...)
     33     [],
     34 )
     36 if TORCH_VERSION_AFTER_2_5:
---> 37     if torch._inductor.config.max_autotune_gemm_search_space == "EXHAUSTIVE":
     38         int8_mm_kernel_configs = [
     39             (BLOCK_M, BLOCK_N, BLOCK_K, num_stages, num_warps)
     40             for BLOCK_M, BLOCK_N, BLOCK_K in itertools.product(
   (...)
     44             for num_warps in [2, 4, 8]
     45         ]
     48 # Baseline configs from pytorch/pytorch
     49 # https://github.com/pytorch/pytorch/blob/7718a1cd4f8e0b794c18a31ebd6353d6273c534e/torch/_inductor/kernel/mm_common.py#L132-L147
     50 # int8_mm_kernel_configs = [
   (...)
     61 #     (256, 128, 128, 3, 8),
     62 # ]

AttributeError: module 'torch._inductor' has no attribute 'config'
```

**Comment by supriyar** [comment]
What is is your torch version?

**Comment by vgoklani** [comment]
We use the docker tag: nvcr.io/nvidia/pytorch:24.12-py3

the installed version of torch is 2.6.0a0+df5bbc09d1.nv24.12

**Comment by supriyar** [comment]
I'm unable to repro, looks like a specific nightly build that might be broken. Are you able to try with a different pytorch version?
cc @jainapurva can you take a look since you did the last release?

**Comment by jainapurva** [comment]
It's not failing with current nightly. Issue might be for a specific nightly build. I'm not able to repro. Are you able to try it with another torch nightly build?

**Comment by vgoklani** [comment]
thanks - this is now fixed in the January docker image: nvcr.io/nvidia/pytorch:25.01-py3
