### PR TITLE
[CPU] skip registration of PT2E inductor passes if mkldnn not available

### LINKED ISSUE #4403: X86InductorQuantizer import crashes on macOS ARM — _is_mkldnn_acl_supported not available
### Description

Importing torchao.quantization.pt2e.quantizer.x86_inductor_quantizer on macOS ARM (Apple Silicon) crashes with:

`AttributeError: '_OpNamespace' 'mkldnn' object has no attribute '_is_mkldnn_acl_supported'`

The module-level code at the bottom of x86_inductor_quantizer.py ([L1632-L1645](https://github.com/pytorch/ao/blob/v0.17.0/torchao/quantization/pt2e/quantizer/x86_inductor_quantizer.py#L1632-L1645)) unconditionally calls `_register_quantization_weight_pack_pass()`, which in turn calls torch.ops.mkldnn._is_mkldnn_acl_supported() in [inductor_passes/x86.py L3221](https://github.com/pytorch/ao/blob/v0.17.0/torchao/quantization/pt2e/inductor_passes/x86.py#L3221). This op is only registered when PyTorch is built with AT_MKLDNN_ENABLED(), which is false for macOS ARM wheels.

This is a regression from the migration out of torch.ao. In torch 2.10, [torch.ao.quantization.quantizer.x86_inductor_quantizer](https://github.com/pytorch/pytorch/blob/v2.10.0/torch/ao/quantization/quantizer/x86_inductor_quantizer.py) did not have this module-level registration and could be imported on any platform without error.

### Steps to reproduce

```python
# On macOS ARM (Apple Silicon) with torch 2.11.0 + torchao 0.17.0
import torchao.quantization.pt2e.quantizer.x86_inductor_quantizer

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  ...
  File ".../torchao/quantization/pt2e/inductor_passes/x86.py", line 3221, in _register_quantization_weight_pack_pass
    if not torch.ops.mkldnn._is_mkldnn_acl_supported():
AttributeError: '_OpNamespace' 'mkldnn' object has no attribute '_is_mkldnn_acl_supported'
```

### Environment

```text
torch: 2.11.0
torchao: 0.17.0
Hardware: Apple Silicon (M1/M2/M3), macOS ARM64
OS: macOS 14.x (Sonoma), ARM64
```

### PR DESCRIPTION
**Pull request by Xia-Weiwen**
fixes https://github.com/pytorch/ao/issues/4403

Add a check and skip the registration if mkldnn not available.

### CODE REVIEW

**Comment by Xia-Weiwen** [comment]
The CI failure (ruff) is caused by https://github.com/pytorch/ao/pull/4294 not this PR.

**Comment by Xia-Weiwen** [comment]
@claude review

**Review by Valentine233 — APPROVED** [review]
